# ----------------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/chdorner/epubinfo
# ----------------------------------------------------------------

language: ruby
script: bundle exec rspec spec
rvm:
  - 2.5.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem install bundler
